/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import DAO.EditoraDAO;
import DAO.LivroDAO;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Autor;
import model.Editora;
import model.Livro;

/**
 *
 * @author Débora Cristina
 */
public class LivroForm extends javax.swing.JFrame {

    /**
     * Creates new form LivroForm
     */
    public LivroForm() {
        initComponents();
        BCodigo.setEnabled(false);
        try {
            livroDAO = new LivroDAO();
            editoraDAO = new EditoraDAO();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BCodigo = new javax.swing.JTextField();
        BTitulo = new javax.swing.JTextField();
        BDescricao = new javax.swing.JTextField();
        BAno = new javax.swing.JTextField();
        BotaoSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        CBEditora = new javax.swing.JComboBox<>();
        btRemover = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela1 = new javax.swing.JTable();
        txtAutorID = new javax.swing.JTextField();
        BBuscar = new javax.swing.JButton();
        BDel = new javax.swing.JButton();
        BAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Código:");

        jLabel2.setText("Titulo:");

        jLabel3.setText("Descrição:");

        jLabel4.setText("Editora:");

        jLabel5.setText("Ano:");

        BotaoSalvar.setText("Salvar");
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Titulo", "Editora", "Ano"
            }
        ));
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);

        CBEditora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        Tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome do Autor"
            }
        ));
        Tabela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabela1);

        txtAutorID.setEnabled(false);

        BBuscar.setText("Buscar");
        BBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarActionPerformed(evt);
            }
        });

        BDel.setText("Del");
        BDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDelActionPerformed(evt);
            }
        });

        BAdd.setText("Add");
        BAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BDescricao))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BAno)
                                    .addComponent(CBEditora, 0, 96, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAutorID, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BAdd)
                                .addGap(18, 18, 18)
                                .addComponent(BDel))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                                .addComponent(BotaoSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(btRemover))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(BCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAutorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BBuscar)
                    .addComponent(BDel)
                    .addComponent(BAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(BTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(BAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(BDescricao)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoSalvar)
                    .addComponent(btRemover))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadComboBox();
        loadTabela();
    }//GEN-LAST:event_formWindowOpened

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
        Livro livro = new Livro();
        livro.setEditora((Editora) CBEditora.getSelectedItem());
        livro.setTitulo(BTitulo.getText());
        livro.setAno(Integer.parseInt(BAno.getText()));
        livro.setDescricao(BDescricao.getText());
        try {
            if (mode.equals("INS")) {
                livroDAO.save(livro);
            } else if (mode.equals("UPD")) {
                livro.setLivro_id(Integer.parseInt(BCodigo.getText()));
                livroDAO.update(livro);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "alvar:" + ex.getMessage());
        }
        loadTabela();
        limparCampos();
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        String id = Tabela.getValueAt(Tabela.getSelectedRow(), 0).toString();
        int livro_id = Integer.parseInt(id);

        try {
            Livro livro = livroDAO.findById(livro_id);
            BCodigo.setText("" + livro_id);
            BTitulo.setText(livro.getTitulo());
            BAno.setText("" + livro.getAno());
            BDescricao.setText(livro.getDescricao());
            CBEditora.getModel().setSelectedItem(livro.getEditora());

            loadTabelaAutores(livro);

        } catch (Exception ex) {
            Logger.getLogger(LivroForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.mode = "UPD";
    }//GEN-LAST:event_TabelaMouseClicked

    private void loadTabelaAutores(Livro livro) throws Exception {
        DefaultTableModel model = (DefaultTableModel) Tabela1.getModel();
        model.setNumRows(0);
        for (Autor autor : livro.getAutores()) {
            String[] linha = {
                "" + autor.getAutor_id(),
                autor.getNome()
            };
            model.addRow(linha);
        }
    }

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        int opt = JOptionPane.showConfirmDialog(this, "Excluir registro?");

        if (opt == JOptionPane.YES_OPTION) {
            Livro livro = new Livro();
            livro.setLivro_id(Integer.parseInt(BCodigo.getText()));

            try {
                livroDAO.delete(livro);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }

            limparCampos();
            loadTabela();
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    private void BBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarActionPerformed
        AutorDialog dialog = new AutorDialog(this, true);
        dialog.setVisible(true);
        txtAutorID.setText("" + dialog.getAutorId());
    }//GEN-LAST:event_BBuscarActionPerformed

    private void BAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAddActionPerformed
        Autor autor = new Autor();
        Livro livro = new Livro();
        autor.setAutor_id(Integer.parseInt(txtAutorID.getText()));
        livro.setLivro_id(Integer.parseInt(BCodigo.getText()));

        try {
            livroDAO.saveAutorLivro(autor, livro);
            livro = livroDAO.findById(livro.getLivro_id());
            loadTabelaAutores(livro);
        } catch (Exception ex) {
            Logger.getLogger(LivroForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BAddActionPerformed

    private void BDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDelActionPerformed
        int opt = JOptionPane.showConfirmDialog(this, "Excluir registro?");

        if (opt == JOptionPane.YES_OPTION) {
            Autor autor = new Autor();
            Livro livro = new Livro();
            autor.setAutor_id(Integer.parseInt(txtAutorID.getText()));
            livro.setLivro_id(Integer.parseInt(BCodigo.getText()));
            try {
                livroDAO.deleteAutorLivro(livro, autor); System.out.println("ola");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }

            this.mode = "INS";

            try {
                 livro = livroDAO.findById(livro.getLivro_id());
                loadTabelaAutores(livro);
            } catch (Exception ex) {
                Logger.getLogger(LivroForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BDelActionPerformed

    private void Tabela1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela1MouseClicked
        int selectd = Tabela1.getSelectedRow();
        txtAutorID.setText(Tabela1.getValueAt(selectd, 0).toString());
    }//GEN-LAST:event_Tabela1MouseClicked

    public void limparCampos() {
        BTitulo.setText("");
        BAno.setText("");
        BDescricao.setText("");
        this.mode = "INS";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LivroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LivroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LivroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LivroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LivroForm().setVisible(true);
            }
        });
    }

    private void loadComboBox() {
        try {
            //PROGRAMAR A BUSCA DE DADOS
            DefaultComboBoxModel model = new DefaultComboBoxModel(new Vector(editoraDAO.findAll()));
            CBEditora.setModel(model);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void loadTabela() {
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();
        model.setNumRows(0);

        try {
            for (Livro livro : livroDAO.findAll()) {
                String linha[] = {
                    "" + livro.getLivro_id(),
                    livro.getTitulo(),
                    livro.getEditora().getNome(),
                    "" + livro.getAno()
                };

                model.addRow(linha);
            }
        } catch (Exception ex) {
            Logger.getLogger(LivroForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private String mode = "INS";
    private LivroDAO livroDAO;
    private EditoraDAO editoraDAO;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAdd;
    private javax.swing.JTextField BAno;
    private javax.swing.JButton BBuscar;
    private javax.swing.JTextField BCodigo;
    private javax.swing.JButton BDel;
    private javax.swing.JTextField BDescricao;
    private javax.swing.JTextField BTitulo;
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JComboBox<String> CBEditora;
    private javax.swing.JTable Tabela;
    private javax.swing.JTable Tabela1;
    private javax.swing.JButton btRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtAutorID;
    // End of variables declaration//GEN-END:variables
}
